// @vitest-environment happy-dom
import { afterEach, describe, expect, it, vi } from "vitest";
import { ApiError, createAbortError } from "../src/api/apiError.js";
import { disposeComponent } from "../src/components/index.js";
import { createWishlistReportHistoryView, createWishlistModerationHistoryView } from "../src/features/admin/wishlistHistoryView.js";
import { createAdminView } from "../src/features/admin/adminAccess.js";
import { createApplicationShell } from "../src/app/applicationShell.js";
import { RouteNames } from "../src/app/routeContracts.js";
import { getSafeReturnTo, isProtectedRoute } from "../src/auth/sessionGuards.js";
import { barrier } from "./sessionTestHelpers.js";
const wishlistId = "019c52dd-56c1-7cc6-8a95-243f3a032e04", reportId = "019c52dd-56c1-7cc6-8a95-243f3a032e05";
/** @type {import("../src/features/admin/wishlistHistoryService.js").ReportEvent} */ const report = { id: reportId, previousStatus: "pending", status: "upheld", note: "<script>Note</script>\nDeux lignes", occurredAt: "2026-10-08T12:00:00Z" };
/** @type {import("../src/features/admin/wishlistHistoryService.js").ModerationEvent} */ const moderation = { id: reportId, action: "suspended", reason: "Motif privé\nMultiligne", occurredAt: report.occurredAt };
/** @type {HTMLElement[]} */ const views = [];
afterEach(() => { views.splice(0).forEach(disposeComponent); document.body.replaceChildren(); });
async function settle() { for (let i = 0; i < 15; i++) await Promise.resolve(); }
/** @param {"report" | "moderation"} [kind] History family. */
function setup(kind = "report") {
  const load = vi.fn(/** @type {(options: import("../src/features/admin/wishlistHistoryService.js").HistoryOptions) => Promise<import("../src/features/admin/wishlistHistoryService.js").HistoryPage<import("../src/features/admin/wishlistHistoryService.js").ReportEvent | import("../src/features/admin/wishlistHistoryService.js").ModerationEvent>>} */ (async ({ page }) => ({ items: [kind === "report" ? report : moderation], currentPage: page, totalCount: 21, totalPages: 2 })));
  const controller = new AbortController();
  const view = kind === "report" ? createWishlistReportHistoryView({ wishlistId, reportId, loadReportHistory: (_id, _reportId, options) => /** @type {Promise<import("../src/features/admin/wishlistHistoryService.js").HistoryPage<import("../src/features/admin/wishlistHistoryService.js").ReportEvent>>} */ (load(options)), signal: controller.signal }) : createWishlistModerationHistoryView({ wishlistId, loadModerationHistory: (_id, options) => /** @type {Promise<import("../src/features/admin/wishlistHistoryService.js").HistoryPage<import("../src/features/admin/wishlistHistoryService.js").ModerationEvent>>} */ (load(options)), signal: controller.signal });
  views.push(view); document.body.append(view);
  /** @param {string} name Command. */ function button(name) { const found = [...view.querySelectorAll("button")].find(button => button.textContent === name); if (!found) throw new Error(name); return found; }
  return { view, load, controller, button };
}
describe("read-only administration histories", () => {
  it.each(["report", "moderation"])("loads freshly and renders %s data safely", async kind => {
    const ui = setup(/** @type {"report" | "moderation"} */ (kind)); expect(ui.view.textContent).toContain("Chargement de l’historique…"); await settle(); expect(ui.load).toHaveBeenCalledExactlyOnceWith({ page: 1, signal: expect.any(AbortSignal) }); expect(ui.view.querySelector("script")).toBeNull(); expect(ui.view.querySelector("time")?.dateTime).toBe(report.occurredAt); expect(ui.view.querySelector("form")).toBeNull(); expect(ui.view.textContent).not.toContain("administratorId"); expect(ui.view.textContent).toContain(kind === "report" ? "En attente → Retenu" : "Liste suspendue"); expect(ui.view.querySelector("a")?.getAttribute("href")).toBe(kind === "report" ? `/admin/reported-wishlists/${wishlistId}/reports/${reportId}` : `/admin/reported-wishlists/${wishlistId}/moderation`);
  });
  it("shows equal-status correction events and omits absent notes", async () => { const ui = setup(); await settle(); ui.load.mockResolvedValueOnce({ items: [{ ...report, status: "pending", note: null }], currentPage: 2, totalCount: 21, totalPages: 2 }); ui.button("Suivant").click(); await settle(); expect(ui.view.textContent).toContain("En attente → En attente"); expect(ui.view.textContent).not.toContain("Note privée"); });
  it.each(["reasonUpdated", "reactivated"])("renders moderation %s without inventing reason", async action => { const ui = setup("moderation"); await settle(); ui.load.mockResolvedValueOnce({ items: [{ ...moderation, action: /** @type {"reasonUpdated" | "reactivated"} */ (action), reason: action === "reactivated" ? null : moderation.reason }], currentPage: 2, totalCount: 21, totalPages: 2 }); ui.button("Suivant").click(); await settle(); expect(ui.view.textContent).toContain(action === "reactivated" ? "Liste réactivée" : "Motif de suspension modifié"); expect(ui.view.textContent?.includes("Motif privé :")).toBe(action !== "reactivated"); });
  it("paginates only explicitly, removes old data while loading and focuses the title", async () => {
    const ui = setup(), gate = barrier(); await settle(); expect(ui.button("Précédent").disabled).toBe(true); ui.load.mockImplementationOnce(async () => { await gate.promise; return { items: [report], currentPage: 2, totalCount: 21, totalPages: 2 }; }); ui.button("Suivant").click(); expect(ui.view.textContent).not.toContain(report.note); expect(ui.view.getAttribute("aria-busy")).toBeNull(); expect(ui.view.querySelector('[aria-busy="true"]')).not.toBeNull(); gate.resolve(); await settle(); expect(ui.load).toHaveBeenLastCalledWith({ page: 2, signal: expect.any(AbortSignal) }); expect(ui.view.textContent).toContain("Page 2 sur 2"); expect(document.activeElement).toBe(ui.view.querySelector("h1")); expect(ui.button("Suivant").disabled).toBe(true); ui.button("Précédent").click(); await settle(); expect(ui.load).toHaveBeenLastCalledWith({ page: 1, signal: expect.any(AbortSignal) });
  });
  it.each([0, 1])("offers explicit recovery from an out-of-range page with %s total pages", async totalPages => { const ui = setup(); await settle(); ui.load.mockResolvedValueOnce({ items: [], currentPage: 2, totalCount: totalPages, totalPages }); ui.button("Suivant").click(); await settle(); expect(ui.load).toHaveBeenCalledTimes(2); ui.button(totalPages ? "Rejoindre la dernière page" : "Revenir à la première page").click(); await settle(); expect(ui.load).toHaveBeenLastCalledWith({ page: 1, signal: expect.any(AbortSignal) }); });
  it.each(["report", "moderation"])("shows the empty %s state without controls", async kind => { const ui = setup(/** @type {"report" | "moderation"} */ (kind)); await settle(); ui.load.mockResolvedValueOnce({ items: [], currentPage: 2, totalCount: 0, totalPages: 0 }); ui.button("Suivant").click(); await settle(); ui.load.mockResolvedValueOnce({ items: [], currentPage: 1, totalCount: 0, totalPages: 0 }); ui.button("Revenir à la première page").click(); await settle(); expect(ui.view.textContent).toContain(kind === "report" ? "Aucun historique de traitement pour ce signalement" : "Aucun historique de modération pour cette liste"); expect(ui.view.querySelector("ol")).toBeNull(); expect(ui.view.querySelector("button")).toBeNull(); });
  it.each([401, 429, 503])("recovers explicitly from error %s without stale data or backend text", async statusCode => { const ui = setup(); await settle(); ui.load.mockRejectedValueOnce(new ApiError({ kind: "http", statusCode, correlationId: reportId, retryAfterSeconds: 8, validationErrors: [{ propertyName: "unknown", errorMessage: "SECRET" }] })); ui.button("Suivant").click(); await settle(); expect(ui.view.textContent).not.toContain(report.note); expect(ui.view.textContent).not.toContain("SECRET"); expect(document.activeElement?.getAttribute("role")).toBe("alert"); if (statusCode === 429) expect(ui.view.textContent).toContain("8 seconde(s)"); ui.button("Réessayer").click(); await settle(); expect(document.activeElement).toBe(ui.view.querySelector("h1")); expect(ui.load).toHaveBeenCalledTimes(3); });
  it.each([403, 404])("removes private events on terminal %s and aborts lifetime", async statusCode => { const ui = setup(); await settle(); ui.load.mockRejectedValueOnce(new ApiError({ kind: "http", statusCode })); ui.button("Suivant").click(); await settle(); expect(ui.view.textContent).toContain(statusCode === 403 ? "Accès administrateur requis" : "Signalement introuvable"); expect(ui.view.textContent).not.toContain(report.note); expect(ui.load.mock.calls[0][0].signal.aborted).toBe(true); if (statusCode === 404) expect(ui.view.querySelector("a")).not.toBeNull(); });
  it("reports a missing moderation list", async () => { const ui = setup("moderation"); await settle(); ui.load.mockRejectedValueOnce(new ApiError({ kind: "http", statusCode: 404 })); ui.button("Suivant").click(); await settle(); expect(ui.view.textContent).toContain("Liste introuvable"); });
  it.each([false, true])("ignores late completion or rejection after disposal: %s", async failure => { const ui = setup(), gate = barrier(); await settle(); ui.load.mockImplementationOnce(async () => { await gate.promise; if (failure) throw new ApiError({ kind: "network" }); return { items: [report], currentPage: 2, totalCount: 21, totalPages: 2 }; }); ui.button("Suivant").click(); ui.controller.abort(); gate.resolve(); await settle(); expect(ui.view.textContent).toBe(""); });
  it("does not load with an aborted signal and ignores AbortError", async () => { const controller = new AbortController(); controller.abort(); const load = vi.fn(); const view = createWishlistModerationHistoryView({ wishlistId, loadModerationHistory: load, signal: controller.signal }); views.push(view); expect(load).not.toHaveBeenCalled(); const next = createWishlistModerationHistoryView({ wishlistId, loadModerationHistory: async () => { throw createAbortError(); } }); views.push(next); await settle(); expect(next.querySelector("[role=alert]")).toBeNull(); });
  it.each([RouteNames.WishlistReportHistory, RouteNames.WishlistModerationHistory])("keeps %s private and Modération active without expanding returnTo", name => { expect(isProtectedRoute(name)).toBe(true); expect(getSafeReturnTo(`/admin/reported-wishlists/${wishlistId}/moderation/history`)).toBe("/lists"); const shell = createApplicationShell(); shell.setSession(/** @type {import("../src/auth/sessionManager.js").SessionSnapshot} */ (/** @type {unknown} */ ({ status: "authenticated", user: { id: wishlistId, roles: ["Admin"] }, authenticationPending: false, logoutPending: false }))); shell.setCurrentRoute(/** @type {import("../src/router/router.js").RouteSnapshot} */ (/** @type {unknown} */ ({ name }))); expect(shell.element.querySelector('a[href="/admin/reported-wishlists"]')?.getAttribute("aria-current")).toBe("page"); disposeComponent(shell.element); });
  it("removes the history on account change before a pending read completes", async () => {
    const ui = setup(), gate = barrier(); await settle(); ui.load.mockImplementationOnce(async () => { await gate.promise; return { items: [report], currentPage: 2, totalCount: 21, totalPages: 2 }; }); ui.button("Suivant").click();
    const snapshot = /** @type {import("../src/auth/sessionManager.js").SessionSnapshot} */ (/** @type {unknown} */ ({ status: "authenticated", user: { id: wishlistId, roles: ["Admin"] }, authenticationPending: false, logoutPending: false }));
    /** @type {(state: import("../src/auth/sessionManager.js").SessionSnapshot) => void} */
    let notify = () => {};
    const host = createAdminView({ getSnapshot: () => snapshot, subscribe: callback => { notify = callback; return () => {}; } }, { createView: () => ui.view }); views.push(host); document.body.append(host); notify({ ...snapshot, user: null }); gate.resolve(); await settle(); expect(host.textContent).toContain("Accès administrateur requis"); expect(host.textContent).not.toContain(report.note);
  });
});
