import { test, expect } from "@playwright/test";
import { controlledApi, listId } from "./controlledApi.js";

test("create then delete a list with an explicit confirmation and individual version", async ({ page, context }) => {
  const api = await controlledApi(context);
  api.state.listExists = false;
  await page.goto("/lists");
  await page.getByRole("textbox", { name: /Adresse e-mail/ }).fill("test@example.test");
  await page.getByLabel(/^Mot de passe/).fill("Fixture-only-password-930!");
  await page.getByRole("button", { name: "Se connecter", exact: true }).click();
  await expect(page.getByText("Tu n’as pas encore de liste", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Créer une liste", exact: true }).click();
  await page.getByRole("textbox", { name: /Nom de la liste/ }).fill("Liste créée par le test");
  await page.getByRole("combobox", { name: /Occasion/ }).selectOption("other");
  expect(api.state.listWrites).toBe(0);
  await page.getByRole("button", { name: "Créer ma liste", exact: true }).click();
  await expect(page).toHaveURL(`/lists/${listId}`);
  await expect(page.getByRole("heading", { name: "Liste créée par le test", exact: true })).toBeVisible();
  expect(api.state.listWrites).toBe(1);
  await page.getByRole("link", { name: "Supprimer cette liste", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Supprimer définitivement « Liste créée par le test » ?", exact: true })).toBeVisible();
  expect(api.state.listWrites).toBe(1);
  await page.getByRole("button", { name: "Supprimer définitivement", exact: true }).click();
  await expect(page).toHaveURL("/lists");
  await expect(page.getByText("Tu n’as pas encore de liste", { exact: true })).toBeVisible();
  expect(api.state.listWrites).toBe(2);
  expect(api.unexpected).toEqual([]);
});

test("add, edit and delete the last gift with a native confirmation", async ({ page, context }) => {
  const api = await controlledApi(context);
  api.state.authenticated = true;
  api.state.wishExists = false;
  await page.goto(`/lists/${listId}`);
  await page.getByRole("link", { name: "Ajouter un cadeau", exact: true }).first().click();
  await page.getByRole("textbox", { name: /Nom du cadeau/ }).fill("Carnet test");
  await page.getByRole("textbox", { name: /Prix en euros/ }).fill("19,90");
  await page.getByRole("button", { name: "Ajouter ce cadeau", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Carnet test", exact: true })).toBeVisible();
  expect(api.state.wishWrites).toBe(1);
  await page.getByRole("link", { name: "Modifier le cadeau « Carnet test »", exact: true }).click();
  await expect(page.getByRole("textbox", { name: /Nom du cadeau/ })).toHaveValue("Carnet test");
  await page.getByRole("textbox", { name: /Nom du cadeau/ }).fill("Carnet corrigé");
  await page.getByRole("button", { name: "Enregistrer les modifications", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Modifications enregistrées", exact: true })).toBeVisible();
  expect(api.state.wishWrites).toBe(2);
  await page.getByRole("button", { name: "Supprimer ce cadeau", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await expect(dialog.getByRole("heading")).toContainText("Carnet corrigé");
  await expect(dialog.getByRole("heading")).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Supprimer ce cadeau", exact: true })).toBeFocused();
  expect(api.state.wishWrites).toBe(2);
  await page.getByRole("button", { name: "Supprimer ce cadeau", exact: true }).click();
  await dialog.getByRole("button", { name: "Supprimer définitivement", exact: true }).click();
  await expect(page).toHaveURL(`/lists/${listId}`);
  await expect(page.getByRole("heading", { name: "Carnet corrigé", exact: true })).toHaveCount(0);
  await expect(page.getByRole("link", { name: "Ajouter un cadeau", exact: true }).first()).toBeVisible();
  expect(api.state.wishWrites).toBe(3);
  expect(api.unexpected).toEqual([]);
});
