export const RouteNames = Object.freeze({
  Home: "home",
  Login: "login",
  LinkGoogle: "link-google",
  GoogleReturn: "google-return",
  Register: "register",
  ConfirmEmail: "confirm-email",
  ConfirmEmailChange: "confirm-email-change",
  ForgotPassword: "forgot-password",
  ResetPassword: "reset-password",
  Profile: "profile",
  PasswordChange: "password-change",
  EmailChange: "email-change",
  Lists: "lists",
  NewList: "new-list",
  EditList: "edit-list",
  DeleteList: "delete-list",
  NewWish: "new-wish",
  EditWish: "edit-wish",
  ListDetails: "list-details",
  Reservations: "reservations",
  SharedWishlist: "shared-wishlist",
  SharedWish: "shared-wish",
});

export const RoutePaths = Object.freeze({
  Home: "/",
  Login: "/login",
  LinkGoogle: "/login/link-google",
  GoogleReturn: "/login/google-return",
  Register: "/register",
  ConfirmEmail: "/confirm-email",
  ConfirmEmailChange: "/confirm-email-change",
  ForgotPassword: "/forgot-password",
  ResetPassword: "/reset-password",
  Profile: "/profile",
  PasswordChange: "/profile/password",
  EmailChange: "/profile/email",
  Lists: "/lists",
  NewList: "/lists/new",
  EditList: "/lists/:listId/edit",
  DeleteList: "/lists/:listId/delete",
  NewWish: "/lists/:listId/wishes/new",
  EditWish: "/lists/:listId/wishes/:wishId/edit",
  ListDetails: "/lists/:listId",
  Reservations: "/reservations",
  SharedWishlist: "/shared-wishlists/:shareLinkId",
  SharedWish: "/shared-wishlists/:shareLinkId/wishes/:wishId",
});

export const NavigationItems = Object.freeze([
  Object.freeze({
    label: "Accueil",
    href: RoutePaths.Home,
    routeName: RouteNames.Home,
  }),
  Object.freeze({
    label: "Mes listes",
    href: RoutePaths.Lists,
    routeName: RouteNames.Lists,
  }),
  Object.freeze({
    label: "Mes réservations",
    href: RoutePaths.Reservations,
    routeName: RouteNames.Reservations,
  }),
  Object.freeze({
    label: "Mon profil",
    href: RoutePaths.Profile,
    routeName: RouteNames.Profile,
  }),
  Object.freeze({
    label: "Connexion",
    href: RoutePaths.Login,
    routeName: RouteNames.Login,
  }),
  Object.freeze({
    label: "S’inscrire",
    href: RoutePaths.Register,
    routeName: RouteNames.Register,
  }),
]);
